import type { Metadata } from "next";
import "./globals.css";
import Header from "@/component/header/header";
import { Provider } from "react-redux";
import { store } from "@/redux/store";
import { Providers } from "@/redux/provider";
export const metadata: Metadata = {
  title: "Shoppers",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Providers>
        <body>
          <Header />
          {children}
        </body>
      </Providers>
    </html>
  );
}
